### ISSUE TITLE
Not (yet?) compatible with IntelliJ 2021.2

### ISSUE THREAD

**Issue by transentia** [SJrX/systemdUnitFilePlugin#111]
At startup IntelliJ disables this plugin with a message:

![image](https://user-images.githubusercontent.com/105110/123615823-01d6d200-d849-11eb-8d5b-5a6343dcc464.png)

The plugins page has:

![image](https://user-images.githubusercontent.com/105110/123615292-8117d600-d848-11eb-8767-5198656d97e7.png)

IntelliJ version info:

```
IntelliJ IDEA 2021.2 EAP (Ultimate Edition)
Build #IU-212.4416.7, built on June 23, 2021
```

**Comment by SJrX** [comment]
Thanks should be downloadable in the next few days.

**Comment by transentia** [comment]
Not sure whether to report this as a different issue...but I just tried 0.33 under the latest EAP and got:

![image](https://user-images.githubusercontent.com/105110/135825122-f6f16cd5-1c09-4e52-a675-3982789df33c.png)
