### ISSUE TITLE
Stop warning absolute path for "-" prefix path

### ISSUE THREAD

**Issue by terryding77** [SJrX/systemdUnitFilePlugin#141]
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/11759109/174075329-75090954-943f-4acf-87cc-de56a674edd9.png">
As document says

`If the executable path is prefixed with "-", an exit code of the command normally considered a failure (i.e. non-zero exit status or abnormal exit due to signal) is recorded, but has no further effect and is considered equivalent to success.`

maybe we should make a new regex to support "-" prefix to check if absolute path or not.
```
        "docker-compose" ⚠️
        "-docker-compose" ⚠️
        "/sbin/docker-compose" ✅
        "-/sbin/docker-compose" ✅
```

**Comment by SJrX** [comment]
Thanks for the report, I think we could change the regex here. https://github.com/SJrX/systemdUnitFilePlugin/blob/26e7a370577a1a27cbb3498ab45411dc183f9107/src/main/java/net/sjrx/intellij/plugins/systemdunitfiles/semanticdata/optionvalues/ExecOptionValue.java#L24

I unfortunately am on vacation with no laptop, so a fix is likely a couple weeks away :(

**Comment by SJrX** [comment]
A bit more detail about executable prefixes:

![image](https://user-images.githubusercontent.com/1916599/175564622-fb806c47-2d6e-4550-aec8-4fd0760159b1.png)

https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=
