### ISSUE TITLE
PyCharm Unit File Support is missing keywords

### ISSUE THREAD

**Issue by gt6989b** [SJrX/systemdUnitFilePlugin#67]
I get **this key is unrecognized** warning on `StartLimitInterval` and `StartLimitBurst`, which are valid `systemd` config options for restarting the job. Please add to the valid key list. Thank you.

**Comment by SJrX** [comment]
Ah so I couldn't find those sections in the documentation, the reason this bug exists is because they have been moved to the Unit section as of Systemd 229 (https://github.com/systemd/systemd/blob/master/NEWS) .

 * The settings StartLimitBurst=, StartLimitInterval=, StartLimitAction=
          and RebootArgument= have been moved from the [Service] section of
          unit files to [Unit], and they are now supported on all unit types,
          not just service units. Of course, systemd will continue to
          understand these settings also at the old location, in order to
          maintain compatibility.

I'll take a look and see how I can best fix this, the problem is that I generate most of the valid keys from the Systemd documentation and this is kind of annoying to hack in.

**Comment by gt6989b** [comment]
I can confirm that moving them to the *[Unit]* section fixes StartLimitBurst,
but StartLimitInterval still generates a warning even in the *[Unit]*
 section.

**Comment by SJrX** [comment]
Ah I'm going to have to dig into this more. I think this bug is linked.

**Comment by SJrX** [comment]
https://github.com/systemd/systemd/issues/4826

**Comment by SJrX** [comment]
Need to investigate the following unaccounted for options:

Mount.InaccessibleDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Mount.ReadOnlyDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Mount.ReadWriteDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Service.FailureAction
Service.InaccessibleDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Service.PermissionsStartOnly
Service.ReadOnlyDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Service.ReadWriteDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Service.RebootArgument
Service.StartLimitAction https://github.com/systemd/systemd/blob/master/NEWS#L3446
Service.StartLimitBurst  https://github.com/systemd/systemd/blob/master/NEWS#L3446
Service.StartLimitInterval https://github.com/systemd/systemd/blob/master/NEWS#L3446
Socket.InaccessibleDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Socket.ReadOnlyDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Socket.ReadWriteDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Swap.InaccessibleDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Swap.ReadOnlyDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Swap.ReadWriteDirectories https://github.com/systemd/systemd/blob/master/NEWS#L2802
Unit.AssertNull
Unit.BindTo
Unit.ConditionNull
Unit.OnFailureIsolate
Unit.PropagateReloadFrom
Unit.PropagateReloadTo
Unit.RequiresOverridable
Unit.RequisiteOverridable
Unit.StartLimitInterval https://github.com/systemd/systemd/blob/master/NEWS#L3446

**Comment by SJrX** [comment]
Filed bug for: https://github.com/systemd/systemd/issues/11812 missing options.
