### ISSUE TITLE
Add support for IntelliJ 2019.3

### ISSUE THREAD

**Issue by programingjd** [SJrX/systemdUnitFilePlugin#82]

**Comment by SJrX** [comment]
Hrm, thanks for the request.

I took a look at this this morning, but unfortunately I can't even boot up the latest EAP at this point and will ping the IntelliJ developer forum on this topic.

**Comment by SJrX** [comment]
Forum posting for future references: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360005405240-Can-t-start-Plugin-with-IntelliJ-2019-3-EAP

**Comment by SJrX** [comment]
Hrm, this was caused by: https://github.com/JetBrains/Grammar-Kit/issues/215

**Comment by SJrX** [comment]
@programingjd, hrm looks like there are even more changes required for 2019.3? Are you actively using 2019.3 at this point or did you just notice this and file a bug report.

I typically upgrade within days of an actual release, and my guess is that we are 6 weeks away from 2019.3. So I might just hold off until then if it's not actually bothering anyone :)

**Comment by SJrX** [comment]
Note for future self, we need to change our fileType extension point, first change here:
https://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes/api_changes_list_2019.html#changes-in-intellij-platform-20193

**Comment by programingjd** [comment]
Thank you for looking into the issue.
Yes, I am using 2019.3. I am pretty much always on the latest EAP unless I run into show stopper.
Most of the time I am writing Kotlin code and I find that it's quite beneficial to use the EAP for that.
