### ISSUE TITLE
Add support for the upcoming 2020.2

### ISSUE THREAD

**Issue by b1rdex** [SJrX/systemdUnitFilePlugin#93]
PhpStorm 2020.2 Beta
Build #PS-202.6397.25, built on July 16, 2020
PhpStorm EAP User
Expiration date: August 15, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: name.kropp.intellij.makefile, navigate-from-literal, some.awesome, NEON support, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, de.espend.idea.php.generics

**Comment by SJrX** [comment]
Thanks for the report, updating systemd, and hopefully a new version will be out in a few days.
